### ISSUE TITLE
Add /bplugins list, similar to /pl

### ISSUE THREAD

**Issue by rmarmorstein** [dommi2212/BPlugins#1]
It would be useful to have a /bplugins list similar to the Spigot /plugins command.

:)

**Comment by dommi2212** [comment]
Will be added..

**Comment by rmarmorstein** [comment]
Thank you, Wasn't too sure on what you were planning!

**Comment by dommi2212** [comment]
Oh... Just noticed, I misunterstood you:
Just use "/BPlugins" to see all installed plugins.
